Practice htmling of form, table and layout
oldjunior/external-courses pull request #8
Opened 2019-11-03 16:03 UTC by oldjunior

2019-11-08 09:17 UTC, Artem7753 commented on src/ex10_html-css-fundamentals-part2/task-01.html
> +    <img src="img/binary_code.jpg" id="binary" alt="Binary Code">
задание выполнено не до конца

2019-11-08 09:18 UTC, Artem7753 commented on src/ex10_html-css-fundamentals-part2/task-02.html
> +          <label><input type="radio" name="sex" value="m"> male</label>
использовать здесь спан - плохая идея

2019-11-08 09:20 UTC, Artem7753 commented on src/ex10_html-css-fundamentals-part2/task-02.html
> +          <label><input type="checkbox" name="city" value="ryazan"> Ryazan</label>
тоже самое

2019-11-08 09:25 UTC, Artem7753 commented on src/ex10_html-css-fundamentals-part2/task-03.html
> +        <td class="cell customer-name">jhonny aviony</td>
давай каждую первую ячейку выберем псевдоселектором

2019-11-08 09:33 UTC, Artem7753 commented on src/ex10_html-css-fundamentals-part2/task-03.html
> +        <th class="head">customer</th>
странно иметь вложенность с одинаковыми классами

2019-11-08 09:34 UTC, Artem7753 commented on src/ex10_html-css-fundamentals-part2/task-03.html
> +    <link rel="stylesheet" href="css/task-03-2.css">
сделай еще изменение курсора по хуверу

2019-11-08 09:40 UTC, Artem7753 commented on src/ex10_html-css-fundamentals-part2/task-04.html
> +    <footer class="footer">
футера нет в дизайне

2019-11-08 09:41 UTC, Artem7753 commented on src/ex10_html-css-fundamentals-part2/task-04.html
> +    <section class="banner">
растяни на всю ширину

2019-11-08 09:42 UTC, Artem7753 requested changes
в целом ок, немного поправь

2019-11-08 12:56 UTC, oldjunior commented on src/ex10_html-css-fundamentals-part2/task-03.html
> +        <td class="cell customer-name">jhonny aviony</td>
And what if we add a new column with some sort of ID or whatever. Don't we have to capitilalize customer names regardless of their place in the table?

2019-11-08 12:59 UTC, oldjunior commented on src/ex10_html-css-fundamentals-part2/task-03.html
> +    <link rel="stylesheet" href="css/task-03-2.css">
Why do we have to do that to a non-clickable element?

2019-11-08 13:13 UTC, oldjunior commented on src/ex10_html-css-fundamentals-part2/task-02.html
> +          <label><input type="radio" name="sex" value="m"> male</label>
Could you, please, clarify a bit? [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/span) states that span can be used to group elements.

2019-11-11 07:45 UTC, Artem7753 commented on src/ex10_html-css-fundamentals-part2/task-03.html
> +        <td class="cell customer-name">jhonny aviony</td>
вроде по заданию тебе больше ничего не надо добалвять, конкретно в этом случае неплохо было бы выбирать селекторами

2019-11-11 07:46 UTC, Artem7753 commented on src/ex10_html-css-fundamentals-part2/task-02.html
> +          <label><input type="radio" name="sex" value="m"> male</label>
корректно использовать спан для выделения текста, если у тебя внутри него находятся какие то еще структуры, это уже некорректно

2019-11-11 07:48 UTC, Artem7753 commented on src/ex10_html-css-fundamentals-part2/task-03.html
> +    <link rel="stylesheet" href="css/task-03-2.css">
смысл иметь хувер на такой элемент? хочу посмотреть что ты это умеешь. все

2019-11-11 12:43 UTC, oldjunior commented on src/ex10_html-css-fundamentals-part2/task-02.html
> +          <label><input type="radio" name="sex" value="m"> male</label>
Got it, thanks. Changed it.

2019-11-14 20:05 UTC, merged